references:
  - https://mew-ton.github.io/coding-guidelines

logging:
  file: ".kex/kex.log"
  level: info

update:
  ai-skills:
    targets:
      - antigravity
    keywords:
      - coding
      - go