package config

import (
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

type Config struct {
	Root        string  `yaml:"root"`
	BaseURL     string  `yaml:"baseURL,omitempty"`
	RemoteToken string  `yaml:"remoteToken,omitempty"`
	Update      Update  `yaml:"update"`
	Logging     Logging `yaml:"logging,omitempty"`
}

type Logging struct {
	Level string `yaml:"level,omitempty"`
	File  string `yaml:"file,omitempty"`
}

type Update struct {
	Strategies Strategies `yaml:"strategies"`
}

type Strategies map[string]string

func Load(projectRoot string) (Config, error) {
	// 1. Set Defaults
	config := Config{
		Root:    "contents",
		BaseURL: "",
		Update: Update{
			Strategies: Strategies{
				// Defaults for groups will be handled by logic if needed,
				// but here we can initialize empty or set defaults if we want "kex: all" by default?
				// CLI init sets them, so maybe empty here is fine (implies "none" if not set).
				// However, if we want kex documentation to be generated by default even without init?
				// The previous code had "skip" defaults for System Docs.
				// Let's keep it minimal here: defaults are empty.
			},
		},
	}

	configPath := filepath.Join(projectRoot, ".kex.yaml")
	data, err := os.ReadFile(configPath)
	if os.IsNotExist(err) {
		return config, nil
	}
	if err != nil {
		return config, err
	}

	if err := yaml.Unmarshal(data, &config); err != nil {
		return config, err
	}

	return config, nil
}
